version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm prune --production
  post_build:
    commands:
      - cp -r dist/* .
      - rm -r dist *.yml src .env README* tsconfig.json .git* Dockerfile .vscode*
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  name: item-presentation-api-$(date +%Y-%m-%d)